export default {
    LOGS: 1,
    AUTOMESSAGES: 2,
    SUBALERT: 3,
    TEMPLATES: 4,
    MAIN: 5,
    CHANNEL: 6,
    SUBSCRIPTIONS: 7,
    BITS: 8,
    EXTERNAL_SERVICES: 9,
    SUBTRAIN: 10,
    CHANNELBANS: 11,
    SUBDAY: 12,
    SONGREQUESTS: 13
};